// Insurance Manager ABI - Core contract for managing insurance products, policies, and claims
export const INSURANCE_MANAGER_ABI = [
  // View functions
  {
    inputs: [{ name: "productId", type: "uint256" }],
    name: "getProduct",
    outputs: [
      { name: "id", type: "uint256" },
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "premium", type: "uint256" },
      { name: "coverageAmount", type: "uint256" },
      { name: "duration", type: "uint256" },
      { name: "insurer", type: "address" },
      { name: "isActive", type: "bool" },
      { name: "poolBalance", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getActiveProducts",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "policyId", type: "uint256" }],
    name: "getPolicy",
    outputs: [
      { name: "id", type: "uint256" },
      { name: "productId", type: "uint256" },
      { name: "holder", type: "address" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "status", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "holder", type: "address" }],
    name: "getUserPolicies",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "claimId", type: "uint256" }],
    name: "getClaim",
    outputs: [
      { name: "id", type: "uint256" },
      { name: "policyId", type: "uint256" },
      { name: "claimant", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "diseaseType", type: "uint256" },
      { name: "documentHash", type: "bytes32" },
      { name: "status", type: "uint8" },
      { name: "proofVerified", type: "bool" },
      { name: "submittedAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUserClaims",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "insurer", type: "address" }],
    name: "getInsurerClaims",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "isInsurer",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "isAdmin",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  // Write functions
  {
    inputs: [{ name: "productId", type: "uint256" }],
    name: "buyPolicy",
    outputs: [{ name: "policyId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "policyId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "diseaseType", type: "uint256" },
      { name: "documentHash", type: "bytes32" },
      {
        name: "proof",
        type: "tuple",
        components: [
          { name: "a", type: "uint256[2]" },
          { name: "b", type: "uint256[2][2]" },
          { name: "c", type: "uint256[2]" },
        ],
      },
      { name: "publicInputs", type: "uint256[]" },
    ],
    name: "submitClaimWithProof",
    outputs: [{ name: "claimId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "premium", type: "uint256" },
      { name: "coverageAmount", type: "uint256" },
      { name: "duration", type: "uint256" },
    ],
    name: "createProduct",
    outputs: [{ name: "productId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "productId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    name: "fundPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "productId", type: "uint256" },
      { name: "isActive", type: "bool" },
    ],
    name: "setProductActive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "claimId", type: "uint256" }],
    name: "approveClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "claimId", type: "uint256" }],
    name: "rejectClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "claimId", type: "uint256" }],
    name: "payClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "grantInsurerRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "revokeInsurerRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "productId", type: "uint256" },
      { indexed: true, name: "insurer", type: "address" },
    ],
    name: "ProductCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "policyId", type: "uint256" },
      { indexed: true, name: "holder", type: "address" },
      { indexed: true, name: "productId", type: "uint256" },
    ],
    name: "PolicyPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "claimId", type: "uint256" },
      { indexed: true, name: "policyId", type: "uint256" },
      { indexed: true, name: "claimant", type: "address" },
    ],
    name: "ClaimSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "claimId", type: "uint256" },
      { indexed: false, name: "status", type: "uint8" },
    ],
    name: "ClaimStatusChanged",
    type: "event",
  },
] as const;

// Mock USDT ABI - ERC20 token
export const MOCK_USDT_ABI = [
  {
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "amount", type: "uint256" }],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
